# THEORITICAL QUESTIONS

**1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?**

### Purpose of NumPy

NumPy is a fundamental library in Python for scientific computing and data analysis. It provides:

1. **N-dimensional Arrays**: Efficient storage and manipulation of large datasets through its `ndarray` object.
2. **Numerical Operations**: A wide range of mathematical functions for performing calculations on arrays and matrices.

### Advantages of NumPy

1. **Performance**:
   - **Speed**: NumPy operations are implemented in C, making them faster than Python's native operations.
   - **Vectorization**: Enables operations on entire arrays without explicit loops, simplifying code and enhancing speed.

2. **Memory Efficiency**:
   - Uses contiguous memory blocks and fixed data types, leading to lower memory usage compared to Python lists.

3. **Convenience**:
   - Rich functions for array manipulation, including reshaping, slicing, and broadcasting.

4. **Ease of Use**:
   - Intuitive syntax that resembles mathematical notation, making it accessible for scientists and engineers.

5. **Rich Functionality**:
   - Offers advanced mathematical functions, linear algebra routines, and random number generation.

### Enhancing Python's Capabilities

- **Mathematical Functions**: Adds extensive mathematical operations that can be applied directly to arrays.
- **Broadcasting**: Allows operations on arrays of different shapes, simplifying arithmetic.
- **Integration**: Interfaces with C and Fortran for high-performance computations.
- **Advanced Indexing**: Provides advanced indexing and slicing options, enabling complex data manipulations.

In summary, NumPy enhances Python's capabilities for numerical operations, making it a vital tool for data science, machine learning, and scientific research.

**2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?**

In NumPy, both `np.mean()` and `np.average()` compute the average of elements, but they have some differences:

### `np.mean()`
- **Function**: Calculates the arithmetic mean (simple average) of an array.
- **Weights**: Does **not** accept weights.
- **Usage**: Use `np.mean()` when you want a simple, unweighted average of the elements.

### `np.average()`
- **Function**: Computes the weighted average if weights are provided.
- **Weights**: Accepts an optional `weights` argument to compute a weighted mean.
- **Usage**: Use `np.average()` when you need to calculate a weighted average, or when you have different importance for different data points.

### Key Difference
- **`np.mean()`**: Only a simple mean.
- **`np.average()`**: Can compute a weighted mean if weights are provided; otherwise, it behaves like `np.mean()`.

### When to Use:
- Use `np.mean()` for a simple, straightforward average.
- Use `np.average()` if you need to account for varying importance of elements with weights.

**3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.**

In NumPy, you can reverse arrays along different axes using slicing or specific functions. Here are the methods for reversing a 1D and 2D array:

### For 1D Array:
You can reverse a 1D array using slicing:
```python
import numpy as np
arr_1d = np.array([1, 2, 3, 4, 5])
reversed_1d = arr_1d[::-1]
print(reversed_1d)  # Output: [5 4 3 2 1]
```

### For 2D Array:
You can reverse along different axes (rows or columns):

1. **Reverse along rows (axis 0)**:
   ```python
   arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
   reversed_rows = arr_2d[::-1, :]
   print(reversed_rows)
   # Output:
   # [[7 8 9]
   #  [4 5 6]
   #  [1 2 3]]
   ```

2. **Reverse along columns (axis 1)**:
   ```python
   reversed_cols = arr_2d[:, ::-1]
   print(reversed_cols)
   # Output:
   # [[3 2 1]
   #  [6 5 4]
   #  [9 8 7]]
   ```

### Conclusion:
- **1D array**: Use slicing `[::-1]` to reverse.
- **2D array**: Use slicing `[::-1, :]` to reverse rows and `[:, ::-1]` to reverse columns.

**4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.**

### Determining Data Type of Elements in a NumPy Array:
You can determine the data type of elements in a NumPy array using the `dtype` attribute:
```python
import numpy as np
arr = np.array([1, 2, 3])
print(arr.dtype)  # Output: int64 (or int32 depending on the system)
```

### Importance of Data Types in Memory Management and Performance:

1. **Memory Management**:
   - Different data types (e.g., `int32`, `float64`) use different amounts of memory. For example, an `int32` takes 4 bytes, while an `int64` takes 8 bytes.
   - Choosing the appropriate data type for your array can save memory, especially when working with large datasets.

2. **Performance**:
   - Operations on smaller data types (e.g., `int32`) are faster since they require less memory and processing power compared to larger types (e.g., `int64` or `float64`).
   - Properly selecting data types ensures optimal performance, especially in computationally intensive applications.

### Conclusion:
Using the correct data type in NumPy ensures efficient memory usage and enhances computational performance by reducing unnecessary overhead.

**5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?**

### NumPy `ndarray`:
An `ndarray` (N-dimensional array) is the core data structure in NumPy, representing a multi-dimensional, homogeneous array of fixed-size items. It can store elements of the same data type in a grid-like format (1D, 2D, or higher dimensions).

### Key Features of `ndarray`:
1. **Homogeneous**: All elements must be of the same data type (e.g., integers, floats).
2. **Multi-dimensional**: Supports N-dimensional arrays (1D, 2D, 3D, etc.).
3. **Efficient Memory**: Stored in contiguous memory blocks, making operations faster and more memory-efficient.
4. **Vectorized Operations**: Supports fast, element-wise operations without explicit loops.
5. **Broadcasting**: Allows operations on arrays of different shapes without copying data.
6. **Built-in Functions**: Provides many mathematical, statistical, and linear algebra functions.

### Differences from Python Lists:
- **Data Type**: `ndarray` is homogeneous (same data type); Python lists are heterogeneous (different data types).
- **Performance**: `ndarray` is faster and more memory-efficient due to contiguous memory storage and vectorization.
- **Operations**: NumPy allows element-wise operations and broadcasting, whereas Python lists require loops.
- **Fixed Size**: `ndarray` has a fixed size once created; Python lists can grow or shrink dynamically.

### Conclusion:
`ndarray` offers better performance and memory efficiency than Python lists, making it ideal for numerical computations and scientific tasks.

**6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.**

### Performance Benefits of NumPy Arrays Over Python Lists:

1. **Speed**:
   - **Vectorization**: NumPy arrays allow element-wise operations without loops, leveraging highly optimized C and Fortran code. This makes operations significantly faster compared to Python lists, where loops are required for element-wise calculations.
   - **Avoids Overhead**: NumPy arrays reduce Python's internal overhead associated with dynamic typing and memory management.

2. **Memory Efficiency**:
   - **Fixed Data Types**: NumPy arrays store elements of a single data type in contiguous memory, minimizing memory usage. Python lists, in contrast, store references to objects, which adds memory overhead.
   - **Smaller Footprint**: For large datasets, NumPy arrays take up much less memory than Python lists due to their compact storage structure.

3. **Broadcasting**:
   - NumPy supports broadcasting, enabling efficient operations on arrays of different shapes without needing explicit loops or copying data. This reduces both memory usage and execution time.

4. **Optimized Mathematical Functions**:
   - NumPy provides optimized functions for mathematical, statistical, and linear algebra operations, allowing faster execution than implementing these operations manually with Python lists.

### Conclusion:
NumPy arrays provide superior performance in terms of speed and memory efficiency for large-scale numerical operations compared to Python lists, making them essential for scientific computing and data analysis tasks.

**7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output**

### `vstack()` vs `hstack()` in NumPy:

Both `vstack()` and `hstack()` are used to stack arrays, but they differ in how they align and combine arrays.

### 1. **`vstack()` (Vertical Stack)**:
- **Purpose**: Stacks arrays **vertically** (row-wise).
- **Usage**: Arrays are stacked on top of each other (along the vertical axis).
- **Shape Requirement**: Arrays must have the same number of columns.

**Example**:
```python
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.vstack((arr1, arr2))
print(result)
# Output:
# [[1 2 3]
#  [4 5 6]]
```

### 2. **`hstack()` (Horizontal Stack)**:
- **Purpose**: Stacks arrays **horizontally** (column-wise).
- **Usage**: Arrays are stacked side-by-side (along the horizontal axis).
- **Shape Requirement**: Arrays must have the same number of rows.

**Example**:
```python
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.hstack((arr1, arr2))
print(result)
# Output: [1 2 3 4 5 6]
```

### Comparison:
- **`vstack()`**: Stacks arrays along rows, forming a 2D array if used with 1D arrays.
- **`hstack()`**: Stacks arrays along columns, extending them side-by-side.

### Conclusion:
Use `vstack()` when you need to combine arrays vertically (row-wise) and `hstack()` for combining them horizontally (column-wise).

**8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.**
### `fliplr()` vs `flipud()` in NumPy:

Both `fliplr()` and `flipud()` are used to reverse arrays along specific axes, but they work in different directions.

### 1. **`fliplr()` (Flip Left-Right)**:
- **Purpose**: Reverses the order of elements **horizontally** (left-to-right).
- **Effect**: It flips the array along the second axis (columns).
- **Usage**: Works on 2D or higher-dimensional arrays. For 2D arrays, it reverses the order of columns.
- **Example**:
  ```python
  import numpy as np
  arr = np.array([[1, 2, 3], [4, 5, 6]])
  flipped_lr = np.fliplr(arr)
  print(flipped_lr)
  # Output:
  # [[3 2 1]
  #  [6 5 4]]
  ```

### 2. **`flipud()` (Flip Up-Down)**:
- **Purpose**: Reverses the order of elements **vertically** (up-to-down).
- **Effect**: It flips the array along the first axis (rows).
- **Usage**: Works on 2D or higher-dimensional arrays. For 2D arrays, it reverses the order of rows.
- **Example**:
  ```python
  flipped_ud = np.flipud(arr)
  print(flipped_ud)
  # Output:
  # [[4 5 6]
  #  [1 2 3]]
  ```

### Key Differences:
- **`fliplr()`**: Flips the array **horizontally**, reversing columns.
- **`flipud()`**: Flips the array **vertically**, reversing rows.

### Conclusion:
Use `fliplr()` to reverse elements horizontally and `flipud()` to reverse elements vertically, depending on how you want to manipulate the structure of your array.

**9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?**

### `array_split()` in NumPy:

The `array_split()` function in NumPy is used to split an array into multiple sub-arrays. It works similarly to `split()`, but with one key difference—it can handle **uneven splits**.

### Key Functionality:
- **Purpose**: Splits an array into a specified number of sub-arrays.
- **Syntax**: `np.array_split(array, sections)`
  - `array`: The array to be split.
  - `sections`: Number of equal or unequal sub-arrays.

### Handling Uneven Splits:
If the array cannot be split evenly, `array_split()` ensures that the remaining elements are distributed across sub-arrays, making some sub-arrays slightly larger.

For example, if you try to split an array of 7 elements into 3 parts, two parts will have 3 elements, and one will have 1 element.

**Example**:
```python
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
result = np.array_split(arr, 3)
print(result)
# Output:
# [array([1, 2, 3]), array([4, 5]), array([6, 7])]
```

### Conclusion:
- **`split()`**: Requires even splits.
- **`array_split()`**: Handles uneven splits by adjusting the size of sub-arrays, ensuring flexibility when the array size isn’t divisible by the number of sections.




**10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?**

### Vectorization in NumPy:
- **Definition**: Vectorization refers to performing operations on entire arrays (or vectors) without using explicit loops. NumPy uses optimized C and Fortran code to execute these operations.
- **Benefits**:
  - **Faster Execution**: Eliminates Python's slow loops and reduces function call overhead.
  - **Simpler Code**: Allows concise, readable code as array operations are applied directly to the whole array.

**Example**:
```python
import numpy as np
arr = np.array([1, 2, 3, 4])
result = arr * 2  # Multiply each element by 2 without a loop
```

### Broadcasting in NumPy:
- **Definition**: Broadcasting allows NumPy to perform operations on arrays of different shapes by "stretching" the smaller array to match the shape of the larger array, without copying data.
- **Benefits**:
  - **Memory Efficiency**: Saves memory by not requiring explicit copies of arrays.
  - **Speed**: Enables fast element-wise operations between arrays of different shapes.

**Example**:
```python
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1], [2], [3]])
result = arr1 + arr2  # Broadcasting happens here
```

### Contribution to Efficiency:
- **Vectorization**: Speeds up computations by avoiding slow Python loops.
- **Broadcasting**: Allows efficient operations on arrays with different shapes without extra memory overhead.

### Conclusion:
Vectorization and broadcasting make NumPy highly efficient for large-scale numerical operations by leveraging optimized, low-level code and memory-efficient array manipulation.

# PRACTICAL QUESTIONS

**1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.**

In [1]:
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))
print("Original Array:")
print(array)

# Interchange rows and columns (transpose the array)
transposed_array = array.T
print("\nTransposed Array:")
print(transposed_array)


Original Array:
[[51 73 95]
 [70 44 95]
 [69 15 16]]

Transposed Array:
[[51 70 69]
 [73 44 15]
 [95 95 16]]


**2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array**

In [2]:
import numpy as np

# Generate a 1D array with 10 elements
array_1d = np.arange(10)  # or use np.random.randint(0, 100, size=10) for random elements
print("Original 1D Array:")
print(array_1d)

# Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
print("\nReshaped to 2x5 Array:")
print(array_2x5)

# Reshape it into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)
print("\nReshaped to 5x2 Array:")
print(array_5x2)


Original 1D Array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped to 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped to 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


**3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array**

In [3]:
import numpy as np

# Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)
print("Original 4x4 Array:")
print(array_4x4)

# Add a border of zeros around the array
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)
print("\n6x6 Array with Border of Zeros:")
print(array_6x6)


Original 4x4 Array:
[[0.40425158 0.56800549 0.9608272  0.45444091]
 [0.1990855  0.73428485 0.21454941 0.76894839]
 [0.71416221 0.52172199 0.60839645 0.53517124]
 [0.15817139 0.54941395 0.80386155 0.49076509]]

6x6 Array with Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.40425158 0.56800549 0.9608272  0.45444091 0.        ]
 [0.         0.1990855  0.73428485 0.21454941 0.76894839 0.        ]
 [0.         0.71416221 0.52172199 0.60839645 0.53517124 0.        ]
 [0.         0.15817139 0.54941395 0.80386155 0.49076509 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


**4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.**

In [4]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)
print("Array of integers from 10 to 60 with a step of 5:")
print(array)


Array of integers from 10 to 60 with a step of 5:
[10 15 20 25 30 35 40 45 50 55 60]


**5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.**

In [5]:
import numpy as np

# Create a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
upper_case = np.char.upper(array)         # Uppercase
lower_case = np.char.lower(array)         # Lowercase
title_case = np.char.title(array)         # Title case
capitalize_case = np.char.capitalize(array)  # Capitalize first letter

# Display the results
print("Original Array:")
print(array)

print("\nUppercase:")
print(upper_case)

print("\nLowercase:")
print(lower_case)

print("\nTitle Case:")
print(title_case)

print("\nCapitalize:")
print(capitalize_case)


Original Array:
['python' 'numpy' 'pandas']

Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase:
['python' 'numpy' 'pandas']

Title Case:
['Python' 'Numpy' 'Pandas']

Capitalize:
['Python' 'Numpy' 'Pandas']


**6. Generate a NumPy array of words. Insert a space between each character of every word in the array.**

In [6]:
import numpy as np

# Generate a NumPy array of words
words_array = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_words = np.char.join(' ', words_array)

# Display the results
print("Original Array of Words:")
print(words_array)

print("\nWords with Spaces Between Characters:")
print(spaced_words)


Original Array of Words:
['python' 'numpy' 'pandas']

Words with Spaces Between Characters:
['p y t h o n' 'n u m p y' 'p a n d a s']


**7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.**

In [7]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Perform element-wise addition
addition = array1 + array2

# Perform element-wise subtraction
subtraction = array1 - array2

# Perform element-wise multiplication
multiplication = array1 * array2

# Perform element-wise division
division = array1 / array2

# Display the results
print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nElement-wise Addition:")
print(addition)

print("\nElement-wise Subtraction:")
print(subtraction)

print("\nElement-wise Multiplication:")
print(multiplication)

print("\nElement-wise Division:")
print(division)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise Division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


**8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.**

In [8]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:")
print(identity_matrix)

# Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)

# Display the diagonal elements
print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


**9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.**


In [9]:
import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1000, size=100)

# Function to check for prime numbers
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Find all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

# Display the results
print("Array of Random Integers:")
print(random_integers)

print("\nPrime Numbers in the Array:")
print(prime_numbers)


Array of Random Integers:
[605 162 571 669 575 991 816 716 829 171 835 606 448 186 663  45 148 886
 174 345 450 354 360 539 793 967  61 661  93 555 999 677 988 102  32 897
 530 989 109 811 728 392 712 164 234 842  38 853 605 529 445 417 176 333
 707 321 599 279 425 768   7 873 159 469 749 924 488 774 777 411 581 130
 437 604 705 272  28 744 456 525 116 351 124 513 262 873 986 923 690 939
 439 875 174 943 174 164 457 816  23 184]

Prime Numbers in the Array:
[571, 991, 829, 967, 61, 661, 677, 109, 811, 853, 599, 7, 439, 457, 23]


**10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.**

In [11]:
import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
temperatures = np.random.uniform(15, 30, size=30)

# Calculate weekly averages by splitting the array
weekly_averages = []
for i in range(4):
    weekly_avg = np.mean(temperatures[i * 7: (i + 1) * 7])  # First 4 weeks
    weekly_averages.append(weekly_avg)

# Handle the last 2 days as an additional week
last_week_avg = np.mean(temperatures[28:])  # Average of the last 2 days
weekly_averages.append(last_week_avg)

# Display the results
print("Daily Temperatures for a Month:")
print(temperatures)

print("\nWeekly Averages:")
print(weekly_averages)


Daily Temperatures for a Month:
[24.05395056 15.05854526 27.64844702 20.5889216  25.97882285 19.80291118
 21.42966231 23.81313995 21.31380547 21.52005893 18.00200158 18.54704462
 19.68343961 29.20043633 17.47305926 21.59943883 18.83031153 21.36519008
 22.45279382 22.80561684 29.27956308 25.20468824 29.28699075 19.28353863
 16.89101361 27.04892363 21.2252989  21.68314012 28.41411803 17.76333622]

Weekly Averages:
[22.080180110614112, 21.72570378376157, 21.972281918853128, 22.946227696441323, 23.088727124134806]
